# Generated by Django 4.0.2 on 2022-03-22 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Cliente')),
                ('apellido1', models.CharField(max_length=30, verbose_name='Primer apellido del Cliente')),
                ('apellido2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo apellido del Cliente')),
                ('email', models.EmailField(max_length=254, verbose_name='Gmail')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('cod_postal', models.CharField(max_length=5, verbose_name='Código Postal')),
                ('estado', models.BooleanField(default=True, verbose_name='Cliente Activo/No Activo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titular', models.CharField(max_length=255, verbose_name='Titular de la Tarjeta')),
                ('numeroTarjeta', models.CharField(max_length=16, verbose_name='Número de la Tarjeta')),
                ('ccv', models.CharField(max_length=3, verbose_name='CCV')),
                ('caducidad_tarjeta', models.DateField(verbose_name='Caducidad')),
                ('estado', models.BooleanField(default=True, verbose_name='Cliente Activo/No Activo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XhocolatteApp.cliente')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
