# Generated by Django 4.0.4 on 2022-05-12 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('XhocolatteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecificationvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_value', to='XhocolatteApp.product'),
        ),
    ]
