# Generated by Django 4.0.2 on 2022-03-24 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('XhocolatteApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=9, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Cliente')),
                ('apellido1', models.CharField(max_length=30, verbose_name='Primer apellido del Cliente')),
                ('apellido2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo apellido del Cliente')),
                ('email', models.EmailField(max_length=254, verbose_name='Gmail')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('estado', models.BooleanField(default=True, verbose_name='Empleado Activo/No Activo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Encargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEncargo', models.DateTimeField(verbose_name='Fecha de Encargo')),
                ('fechaEntrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('recibido', models.BooleanField(default=False, verbose_name='Recibido')),
                ('estado', models.BooleanField(default=True, verbose_name='Encargo Activo/No Activo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XhocolatteApp.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XhocolatteApp.empleado')),
            ],
            options={
                'verbose_name': 'Encargo',
                'verbose_name_plural': 'Encargos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('existencias', models.IntegerField(verbose_name='Existencias')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('estado', models.BooleanField(default=True, verbose_name='Producto Activo/No Activo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('encargo', models.ManyToManyField(to='XhocolatteApp.Encargo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Pago Activo/No Activo'),
        ),
        migrations.CreateModel(
            name='ProductoEncargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad del Encargo')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('estado', models.BooleanField(default=True, verbose_name='DetalleEncargo Activo/No Activo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('encargo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XhocolatteApp.encargo')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XhocolatteApp.producto')),
            ],
            options={
                'verbose_name': 'detalleEncargo',
                'verbose_name_plural': 'detalleEncargos',
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('costoProduccion', models.FloatField(verbose_name='Coste Producción')),
                ('costesIndirectos', models.FloatField(verbose_name='Costes Indirectos')),
                ('ganancias', models.FloatField(verbose_name='Ganancias')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('estado', models.BooleanField(default=True, verbose_name='Producción Activo/No Activo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XhocolatteApp.producto')),
            ],
            options={
                'verbose_name': 'Produccion',
                'verbose_name_plural': 'Producciones',
            },
        ),
    ]
