# Generated by Django 4.0.2 on 2022-03-25 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('XhocolatteApp', '0003_receta_funcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('unidad', models.CharField(max_length=45, verbose_name='Unidad')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('estado', models.BooleanField(default=True, verbose_name='Receta Activo/No Activo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('receta', models.ManyToManyField(to='XhocolatteApp.Receta')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('estado', models.BooleanField(default=True, verbose_name='Receta Activo/No Activo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('inventario', models.ManyToManyField(to='XhocolatteApp.Inventario')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='ProveedoresInventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inventario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XhocolatteApp.inventario')),
                ('proveedor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XhocolatteApp.proveedor')),
            ],
            options={
                'verbose_name': 'proveedorInventario',
                'verbose_name_plural': 'proveedoresInventario',
            },
        ),
        migrations.CreateModel(
            name='ListaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente', models.CharField(max_length=45, verbose_name='Ingredientes')),
                ('cantidad', models.CharField(max_length=45, verbose_name='Cantidad')),
                ('unidad_medida', models.CharField(max_length=45, verbose_name='Unidad de medida')),
                ('inventario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XhocolatteApp.inventario')),
                ('receta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XhocolatteApp.receta')),
            ],
            options={
                'verbose_name': 'listaIngrediente',
                'verbose_name_plural': 'listaIngredientes',
            },
        ),
    ]
