# Generated by Django 4.0.2 on 2022-03-25 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('XhocolatteApp', '0004_inventario_proveedor_proveedoresinventario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioReceta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingrediente', models.CharField(max_length=45, verbose_name='Ingredientes')),
                ('cantidad', models.CharField(max_length=45, verbose_name='Cantidad')),
                ('unidad_medida', models.CharField(max_length=45, verbose_name='Unidad de medida')),
                ('inventario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XhocolatteApp.inventario')),
                ('receta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XhocolatteApp.receta')),
            ],
            options={
                'verbose_name': 'listaIngrediente',
                'verbose_name_plural': 'listaIngredientes',
            },
        ),
        migrations.DeleteModel(
            name='ListaIngrediente',
        ),
    ]
