# Generated by Django 4.0.2 on 2022-04-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XhocolatteApp', '0005_inventarioreceta_delete_listaingrediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
