# Generated by Django 4.0.4 on 2022-05-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XhocolatteApp', '0009_alter_blogmodel_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogModel',
        ),
    ]
