# Generated by Django 4.0.4 on 2022-05-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XhocolatteApp', '0010_delete_blogmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='en_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(default='hola', max_length=255),
        ),
    ]
