# Generated by Django 4.0.4 on 2022-05-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XhocolatteApp', '0013_alter_producto_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion',
            new_name='nombre',
        ),
    ]
