# Generated by Django 4.0.4 on 2022-05-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XhocolatteApp', '0014_rename_descripcion_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Que rico esta esto', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
