# Generated by Django 4.0.4 on 2022-05-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XhocolatteApp', '0015_producto_descripcion_alter_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='alergenos',
            field=models.TextField(default='Ninguno', verbose_name='Alergenos'),
        ),
    ]
